### PR TITLE
Use GTest as system dependency

### PR DESCRIPTION
**Pull request by SoapGentoo**
* GTest as too many code problems that tend to seep
  into the main consumers, hence silence all warnings
  originating from it.

### CODE REVIEW

**Comment by sarum9in** [comment]
Inspecting project gtest, branch 1.8.0.
Repo name valid: ☑
Branch name valid: ☑
Target branch is not master: ☑
Has readme.txt: ☑
Has LICENSE.build: ☑
Has upstream.wrap: ☑
Has toplevel meson.build: ☑
Repo contains only buildsystem files: ☑
upstream.wrap has directory: ☑
upstream.wrap directory has no path separators: ☑
upstream.wrap has source_url: ☑
upstream.wrap has source_filename: ☑
upstream.wrap source_filename has no path separators: ☑
upstream.wrap has source_hash: ☑
Download url works: ☑
Hash matches: ☑
upstream.wrap directory 'googletest-release-1.8.0' exists: ☑
Patch merges with source: ☑
The Meson build system
Version: 0.46.0.dev1
Source dir: /tmp/tmp_2rlhh06/src/googletest-release-1.8.0
Build dir: /tmp/tmp_2rlhh06/bin
Build type: native build
Project name: gtest
Native C++ compiler: c++ (gcc 7.3.1 "c++ (GCC) 7.3.1 20180406")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Dependency threads found: YES (cached)
Dependency threads found: YES (cached)
Dependency threads found: YES (cached)
Build targets in project: 0
Found ninja-1.8.2 at /usr/bin/ninja
meson setup: ☑
ninja: Entering directory `/tmp/tmp_2rlhh06/bin'
[0/1] Running all tests.
No tests defined.
ninja test: ☑

**Comment by SoapGentoo** [comment]
Compile line:
`-isystem ../subprojects/googletest-release-1.8.0/googlemock -isystem subprojects/googletest-release-1.8.0/googlemock -isystem ../subprojects/googletest-release-1.8.0/googlemock/include -isystem ../subprojects/googletest-release-1.8.0/googletest -isystem subprojects/googletest-release-1.8.0/googletest -isystem ../subprojects/googletest-release-1.8.0/googletest/include`

**Comment by textshell** [comment]
I don't think wraps should change upstream in ways not needed for integration with meson.
Also i think -isystem for headers with templates will suppress warnings some user might care about regarding template parameterisations that could be problematic.

Maybe this should be an option so the wrap does not unconditionally diverge from upstream?

**Comment by SoapGentoo** [comment]
@textshell the same could be said (and is even way more critical) for boost, yet we use `-isystem` for boost?

**Comment by sarum9in** [comment]
> I don't think wraps should change upstream in ways not needed for integration with meson.

@textshell I don't think `-isystem` changes upstream. It is the way we *use* upstream, aka if you have `gtest` installed in `/usr/include` I believe we get the same behavior as `-isystem` from local directory, right? Also it suppresses warnings inside `gtest`, but should not suppress warnings if you generate them but incorrect usage of `gtest` in your own code.

**Comment by jpakkane** [comment]
As a data point: every single time we have tried to use `-isystem` instead of `-I` by default (in general, not just for gtest), it has broken something for someone and we have had to take it out. Be prepared to do the same if this backfires.

**Comment by sarum9in** [comment]
Let's give it a try then.

**Review by nirbheek — APPROVED** [review]
Let's do it!

**Pull request merged**
