### PR TITLE
Align GTest and GMock with upstream pkgconfig

### PR DESCRIPTION
**Pull request by SoapGentoo**

### CODE REVIEW

**Comment by jpakkane** [comment]
Is this for 1.8.0 or trunk or something else?

**Comment by SoapGentoo** [comment]
good point, this is for trunk, 1.8.0 doesn't contain pc files. Suggestions?

**Comment by jpakkane** [comment]
Wrapdb only works on releases so we would need to have a 1.9.0 or somesuch release until we can do this.

On the other hand this could be submitted upstream...

**Comment by SoapGentoo** [comment]
The pkgconfig stuff is obviously in trunk, but the main point remains: even in 1.8.0 gmock includes `gtest-all.cc`, so my initial addition of gmock did not mimick upstream gmock correctly.

**Comment by jpakkane** [comment]
Assuming this does not cause problems and the description is updated to mention that the .pc files are in trunk but not this release, I'm fine with merging this.

**Comment by SoapGentoo** [comment]
@jpakkane documented now

**Pull request merged**
